-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fxp_sqrt_top_fxp_sqrt_top_Pipeline_VITIS_LOOP_89_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln82 : IN STD_LOGIC_VECTOR (27 downto 0);
    s_V_1_out : OUT STD_LOGIC_VECTOR (30 downto 0);
    s_V_1_out_ap_vld : OUT STD_LOGIC;
    q_V_1_out : OUT STD_LOGIC_VECTOR (28 downto 0);
    q_V_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fxp_sqrt_top_fxp_sqrt_top_Pipeline_VITIS_LOOP_89_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv31_3 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000011";
    constant ap_const_lv29_1 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln89_fu_121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sub_ln91_fu_133_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln91_reg_316 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal q_V_fu_58 : STD_LOGIC_VECTOR (28 downto 0);
    signal q_V_1_fu_254_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal q_star_V_fu_62 : STD_LOGIC_VECTOR (28 downto 0);
    signal r_V_5_fu_246_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal s_V_fu_66 : STD_LOGIC_VECTOR (30 downto 0);
    signal s_V_3_fu_222_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln82_cast_fu_94_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_fu_70 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_2_fu_127_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal r_V_fu_170_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal ret_V_fu_178_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln91_fu_167_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal shl_ln1496_fu_161_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal r_V_1_fu_184_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal r_V_2_fu_196_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal ret_V_1_fu_204_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal r_V_3_fu_210_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_153_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_V_2_fu_216_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal s_V_1_fu_190_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln1031_fu_230_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln1031_1_fu_234_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1031_fu_238_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fxp_sqrt_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fxp_sqrt_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln89_fu_121_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_70 <= i_2_fu_127_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_70 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    q_V_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    q_V_fu_58 <= ap_const_lv29_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    q_V_fu_58 <= q_V_1_fu_254_p2;
                end if;
            end if; 
        end if;
    end process;

    q_star_V_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    q_star_V_fu_62(1) <= '0';
                    q_star_V_fu_62(2) <= '0';
                    q_star_V_fu_62(3) <= '0';
                    q_star_V_fu_62(4) <= '0';
                    q_star_V_fu_62(5) <= '0';
                    q_star_V_fu_62(6) <= '0';
                    q_star_V_fu_62(7) <= '0';
                    q_star_V_fu_62(8) <= '0';
                    q_star_V_fu_62(9) <= '0';
                    q_star_V_fu_62(10) <= '0';
                    q_star_V_fu_62(11) <= '0';
                    q_star_V_fu_62(12) <= '0';
                    q_star_V_fu_62(13) <= '0';
                    q_star_V_fu_62(14) <= '0';
                    q_star_V_fu_62(15) <= '0';
                    q_star_V_fu_62(16) <= '0';
                    q_star_V_fu_62(17) <= '0';
                    q_star_V_fu_62(18) <= '0';
                    q_star_V_fu_62(19) <= '0';
                    q_star_V_fu_62(20) <= '0';
                    q_star_V_fu_62(21) <= '0';
                    q_star_V_fu_62(22) <= '0';
                    q_star_V_fu_62(23) <= '0';
                    q_star_V_fu_62(24) <= '0';
                    q_star_V_fu_62(25) <= '0';
                    q_star_V_fu_62(26) <= '0';
                    q_star_V_fu_62(27) <= '0';
                    q_star_V_fu_62(28) <= '0';
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                                        q_star_V_fu_62(28 downto 1) <= r_V_5_fu_246_p3(28 downto 1);
                end if;
            end if; 
        end if;
    end process;

    s_V_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    s_V_fu_66 <= zext_ln82_cast_fu_94_p1;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    s_V_fu_66 <= s_V_3_fu_222_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln89_fu_121_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sub_ln91_reg_316 <= sub_ln91_fu_133_p2;
            end if;
        end if;
    end process;
    q_star_V_fu_62(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln89_fu_121_p2)
    begin
        if (((icmp_ln89_fu_121_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_70)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_70;
        end if; 
    end process;

    i_2_fu_127_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv5_1));
    icmp_ln89_fu_121_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv5_1E) else "0";
    q_V_1_fu_254_p2 <= (r_V_5_fu_246_p3 or ap_const_lv29_1);
    q_V_1_out <= q_V_fu_58;

    q_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln89_fu_121_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln89_fu_121_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            q_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            q_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_V_1_fu_184_p2 <= std_logic_vector(shift_left(unsigned(ret_V_fu_178_p2),to_integer(unsigned('0' & zext_ln91_fu_167_p1(31-1 downto 0)))));
    r_V_2_fu_196_p3 <= (q_star_V_fu_62 & ap_const_lv2_0);
    r_V_3_fu_210_p2 <= std_logic_vector(shift_left(unsigned(ret_V_1_fu_204_p2),to_integer(unsigned('0' & zext_ln91_fu_167_p1(31-1 downto 0)))));
    r_V_5_fu_246_p3 <= (select_ln1031_fu_238_p3 & ap_const_lv1_0);
    r_V_fu_170_p3 <= (q_V_fu_58 & ap_const_lv2_0);
    ret_V_1_fu_204_p2 <= (r_V_2_fu_196_p3 or ap_const_lv31_3);
    ret_V_fu_178_p2 <= (r_V_fu_170_p3 or ap_const_lv31_1);
    s_V_1_fu_190_p2 <= std_logic_vector(unsigned(shl_ln1496_fu_161_p2) - unsigned(r_V_1_fu_184_p2));
    s_V_1_out <= s_V_fu_66;

    s_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln89_fu_121_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln89_fu_121_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            s_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    s_V_2_fu_216_p2 <= std_logic_vector(unsigned(r_V_3_fu_210_p2) + unsigned(shl_ln1496_fu_161_p2));
    s_V_3_fu_222_p3 <= 
        s_V_2_fu_216_p2 when (tmp_fu_153_p3(0) = '1') else 
        s_V_1_fu_190_p2;
    select_ln1031_fu_238_p3 <= 
        trunc_ln1031_fu_230_p1 when (tmp_fu_153_p3(0) = '1') else 
        trunc_ln1031_1_fu_234_p1;
    shl_ln1496_fu_161_p2 <= std_logic_vector(shift_left(unsigned(s_V_fu_66),to_integer(unsigned('0' & ap_const_lv31_1(31-1 downto 0)))));
    sub_ln91_fu_133_p2 <= std_logic_vector(signed(ap_const_lv5_1D) - signed(ap_sig_allocacmp_i_1));
    tmp_fu_153_p3 <= s_V_fu_66(30 downto 30);
    trunc_ln1031_1_fu_234_p1 <= q_V_fu_58(28 - 1 downto 0);
    trunc_ln1031_fu_230_p1 <= q_star_V_fu_62(28 - 1 downto 0);
    zext_ln82_cast_fu_94_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln82),31));
    zext_ln91_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln91_reg_316),31));
end behav;
