function RTW_SidParentMap() {
    this.sidParentMap = new Array();
    this.sidParentMap["am_demod_hdl_coder:72"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:59"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:63"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:379"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:62"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:50"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:47"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:58"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:73"] = "am_demod_hdl_coder:71";
    this.sidParentMap["am_demod_hdl_coder:380"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:381"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:382"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:383"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:384"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:385"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:386"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:387"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:388"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:389"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:390"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:391"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:392"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:393"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:394"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:395"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:396"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:397"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:398"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:399"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:400"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:401"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:402"] = "am_demod_hdl_coder:379";
    this.sidParentMap["am_demod_hdl_coder:403"] = "am_demod_hdl_coder:379";
    this.getParentSid = function(sid) { return this.sidParentMap[sid];}
}
    RTW_SidParentMap.instance = new RTW_SidParentMap();
