SLStudio.Utils.RemoveHighlighting(get_param('am_demod_hdl_coder', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_am_demod_hdl_coder', 'handle'));
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Sqrt', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Square', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Sum', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Product_to_gain', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SectIn2', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SectOut1', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA21', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA21_outbuff', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA22', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA22_outbuff', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA31', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA31_outbuff', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA32', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA32_outbuff', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB21', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB22', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB31', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB32', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/s(1)', 0, 1, '');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/s(2)', 0, 1, '');
