open_system('gm_am_demod_hdl_coder');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF', 0, 1, 'cp : 188.867 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/Sqrt', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Sqrt', 0, 1, 'cp : 287.679 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/Square', 'user1');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Square', 0, 1, 'cp : 14.851 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/Sum', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Sum', 0, 1, 'cp : 305.722 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/Product_to_gain', 'user1');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/Product_to_gain', 0, 1, 'cp : 307.191 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SectIn2', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SectIn2', 0, 1, 'cp : 101.859 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SectOut1', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SectOut1', 0, 1, 'cp : 101.859 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA21', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA21', 0, 1, 'cp : 47.73 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA21_outbuff', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA21_outbuff', 0, 1, 'cp : 47.73 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA22', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA22', 0, 1, 'cp : 134.738 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA22_outbuff', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA22_outbuff', 0, 1, 'cp : 134.738 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA31', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA31', 0, 1, 'cp : 65.773 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA31_outbuff', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA31_outbuff', 0, 1, 'cp : 65.773 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA32', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA32', 0, 1, 'cp : 152.781 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA32_outbuff', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumA32_outbuff', 0, 1, 'cp : 152.781 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB21', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB21', 0, 1, 'cp : 83.816 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB22', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB22', 0, 1, 'cp : 170.824 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB31', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB31', 0, 1, 'cp : 101.859 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB32', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/SumB32', 0, 1, 'cp : 188.867 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/s(1)', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/s(1)', 0, 1, 'cp : 29.687 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_am_demod_hdl_coder/AM demodulator/LPF/s(2)', 'user2');
annotate_port('gm_am_demod_hdl_coder/AM demodulator/LPF/s(2)', 0, 1, 'cp : 116.695 ns');
